<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Authenticated' => '已认证',
    'Settings' => '设置',
    'Create' => '创建',
    'Manage Authentication' => '实名认证管理',
    'Operation' => '操作',
    'Passed' => '通过',
    'Pending review' => '待审核',
    'Refuse' => '拒绝',
    'Enable Machine Review' => '启用机器审核',
    'idCard Url' => '图片访问URL',
    'idCard Save Path' => '图片存储路径',
    'Machine Review Code' => '阿里云图像识别接口AppCode',
    'Rejected' => '已拒绝',
    'Reset' => '重置',
    'Search' => '搜索',
    'The requested page does not exist.' => '请求的页面不存在',
    'Update' => '更新',
    'Update Authentication' => '检查认证',
    'Update success.' => '更新成功',
    'Agree and accept Service Agreement and Privacy Policy' => '同意并接受 服务协议 和 隐私政策',
    'Agree and accept {serviceAgreement} and {privacyPolicy}' => '同意并接受 {serviceAgreement} 和 {privacyPolicy}',
    'Army ID' => '军官证',
    'Authentication' => '实名认证',
    'Choose file' => '选择文件',
    'Created At' => '创建文件',
    'Email' => '邮箱',
    'Failed Reason' => '拒绝原因',
    'Failure reason:' => '失败原因:',
    'File has to be smaller than 2MB' => '文件最大是2M。',
    'Full Name' => '真实姓名',
    'HKMC ID' => '港澳居民通行证',
    'ID Card' => '身份证',
    'Id Card' => '证件号码',
    'Id Card Image' => '证件照片',
    'Id Type' => '证件类型',
    'Passport ID' => '护照',
    'Passport cover' => '身份证件正面',
    'Passport person page' => '身份证件反面',
    'Passport self holding' => '身份证件照片',
    'Privacy Policy' => '隐私政策',
    'Service Agreement' => '服务条款',
    'Sorry, after passing your review, the information you submitted has not been approved. Please check the information and submit it again.' => '抱歉，经过我们的审核您提交的资料未通过审核，请核实一下资料信息,再次提交。',
    'Status' => '状态',
    'Submit' => '提交',
    'Taiwan ID' => '台湾居民通行证',
    'Updated At' => '更新时间',
    'User Id' => '用户ID',
    'Verify Code' => '验证码',
    'Your application is submitted successfully! We will be processed within three working days, the results will be processed by mail, station message to inform you, if in doubt please contact the official administrator.' => '您的申请提交成功！我们会在三个工作日内处理，处理结果会通过邮件、站内消息方式通知您，如有疑问请联系官方管理员。',
    '{attribute} must be selected.' => '{attribute}必须选中。',
];
